name: Build and Test

permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build_and_test:
    name: Build and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: docker build .crossbar -t wampy/crossbar
      - run: docker run --rm --name crossbar -d -p 8888:8888 wampy/crossbar
      - run: until docker logs crossbar | grep -qm 1 "NODE_BOOT_COMPLETE"; do sleep 0.2 ; done
      - run: npm ci
      - run: npm run build
      - run: npm run typecheck
      - run: npm run lint
      - run: npm test
      - name: Create test coverage report
        if: matrix.node-version == 24
        run: npx c8 report --reporter=lcovonly
      - name: Coveralls
        if: matrix.node-version == 24
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
